export const API_URL = "http://18.118.90.192/"

export const API_LOGIN = API_URL+"api/v1/data/login-student";
export const API_TEACHINGPLANUNIT = API_URL+"api/v1/teaching-plan/getTeachingPlanForUnit"


export const API_ASSIGNMENT = API_URL+"api/v1/assignment/getAssignments"
export const API_GETACADEMICYEAR = API_URL+"api/v1/data/getAcademicYears"
export const API_ATTENDANCEMONTHWISEOUNT =API_URL+"api/v1/attendance/studentAttenDanceMonthWiseCount"
export const API_ATTENDANCEMONTH = API_URL+"api/v1/attendance/studentAttenDanceMonthWise"
export const API_EVENT = API_URL+"api/v1/event/events"
export const API_FORGET = API_URL+"api/v1/data/studentForgetPassword"
export const API_VALIDATEFORGET = API_URL+"api/v1/data/validateForgetPasswordOtp"
export const API_RESETPASSWORD = API_URL+"api/v1/data/resetStudentPassword"
export const API_MAINSCHOLARSHIP = API_URL+"api/v1/scholarship/getScholarshipType"
export const API_FIELD = API_URL+"api/v1/scholarship/appFiedlListForScholarship"
export const API_VIEWSTUDENT = API_URL+"api/v1/scholarship/viewStudentScholarship"
export const API_TEACHINGPLAN = API_URL+"api/v1/teaching-plan/getAllSyllabus"
export const API_CLASSTIMETABLE = API_URL+"api/v1/standard/timetableForSection"
export const API_EXAMTIMETABLE = API_URL+"api/v1/exam/getExamTimetable"
export const API_ASSIGNMENTSUBJECT = API_URL+"api/v1/assignment/getAssignmentSubjects"
export const API_ASSIGNMENTTOPICS = API_URL+"api/v1/assignment/getAssignmentTopics"
export const API_ATTENDANCEPERIOD =  API_URL+"api/v1/attendance/studentAttenDancePeriod"
export const API_GALLERY =  API_URL+"api/v1/gallery/getGalleryList"
export const API_UPLOADASSIGNMENT =  API_URL+"api/v1/assignment/studentUploadAssignment"
export const API_ATTENDANCEPERCENTAGE =  API_URL+"api/v1/assignment/studentAttenDancePrecentage"


export const API_GETSEMESTER = API_URL+"api/v1/college/getSemesters"
export const API_GETSUBJECTCOLLEGE = API_URL+"api/v1/teaching-plan/getAllSyllabusCollege"
export const API_GETUNITSUBJECTCOLLEGE = API_URL+"api/v1/teaching-plan/getAllUnitSubjectCollege"
export const API_EXAMTIMETABLECOLLEGE = API_URL+"api/v1/exam/getExamTimetableCollege"
export const API_ATTENDANCEPERIODCOLLEGE =  API_URL+"api/v1/attendance/studentAttenDancePeriodCollege"
export const API_ATTENDANCEPERCENTAGECOLLEGE =  API_URL+"api/v1/attendance/studentAttenDancePrecentageCollege"
export const API_MONTHWISECOUNTCOLLEGE =API_URL+"api/v1/attendance/studentAttenDanceMonthWiseCountCollege"
export const API_ATTENDANCEMONTHWISECOLLEGE = API_URL+"api/v1/attendance/studentAttenDanceMonthWiseCollege"
export const API_CLASSTIMETABLECOLLEGE = API_URL+"api/v1/standard/timetableForSectionCollege"
export const API_TEACHINGPLANCOLLEGE = API_URL+"api/v1/teaching-plan/getAllSyllabusCollege"
export const API_ASSESSMENT = API_URL+'api/v1/college/studentAssessmentReport'
export const API_ASSIGNMENT_COLLEGE = API_URL+"api/v1/assignment/getAssignmentsCollege"
export const API_CIRCULAR_COLLEGE = API_URL+"api/v1/circular/getCircularList"
export const API_CIRCULAR_DETAIL_COLLEGE = API_URL+"api/v1/circular/getCircularDetail"
export const API_COMPLIANT_UPLOAD = API_URL+'api/v1/complaint/createComplaintAndFeedback'
export const API_SERVICE_REQUEST = API_URL+'api/v1/service-request/createServiceRequest'
export const API_SERVICE_TYPE = API_URL+'api/v1/service-request/getServiceRequestTypes'
export const API_SERVICE_GETLIST = API_URL+'api/v1/service-request/getServiceRequestList'
export const API_UPLOAD_ASSIGNMENT = API_URL+'api/v1/assignment/studentUploadAssignmentCollege'
export const API_UPLOAD_STUDENT = API_URL+'api/v1/update-student-profile'
export const API_VIEW_STUDENT = API_URL+'api/v1/studentProfile'
export const API_GET_STUDENT_SCHOLARSHIP = API_URL+'api/v1/scholarship/getScholarshipStudentDetails'
export const API_GET_IFSCCODE = API_URL+'api/v1/data/validateIfscCode'
export const API_GET_UPDATE_SCHLOARSHIP = API_URL+'api/v1/scholarship/createStudentScholarship'
export const API_GET_FEES = API_URL+'api/v1/fees/getFeesList'
export const API_LEAVE_REQUEST = API_URL+'api/v1/leave/createLeaveRequest'
export const API_INSTITUTE = API_URL+'api/v1/info/instituteInfo'
export const API_NOTIFICATIONTYPE = API_URL+'api/v1/notification/notificationType'
export const API_NOTIFICATION = API_URL+'api/v1/notification/getNotificationList'
export const API_NOTIFICATIONREAD = API_URL+'api/v1/notification/readNotification'
export const API_CONCERNSUBTYPE = API_URL+'api/v1/complaint/getConcernSubType'
export const API_CONCERNTYPE = API_URL+'api/v1/complaint/getConcernType'
export const API_LEAVEODTYPE = API_URL+'api/v1/leave/getLeaveSubType'